# Generated by Django 5.1.2 on 2025-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_facebook_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="stream_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("twitch", "Twitch"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("telegram", "Telegram"),
                ],
                max_length=50,
            ),
        ),
    ]
