# Generated by Django 5.1.2 on 2025-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_socialaccount_stream_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="rtmp_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("twitch", "Twitch"),
                    ("instagram", "Instagram"),
                    ("tiktok", "Tiktok"),
                    ("telegram", "Telegram"),
                ],
                max_length=50,
            ),
        ),
    ]
