version: "3.9"
services:
  web:
    build: .
    container_name: streamlab_web
    command: gunicorn streamlab.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - appnet

  celery:
    build: .
    container_name: streamlab_celery
    command: celery -A streamlab worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - appnet

  db:
    image: postgres:13
    container_name: streamlab_db
    environment:
      POSTGRES_DB: streamlab
      POSTGRES_USER: streamlab_user
      POSTGRES_PASSWORD: streamlab_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:6-alpine
    container_name: streamlab_redis
    networks:
      appnet:
        aliases:
          - redis

volumes:
  pgdata:

networks:
  appnet:
