version: "3.9"
services:
  web:
    build: .
    container_name: streamlab_web
    command: gunicorn streamlab.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - appnet

  celery:
    build: .
    container_name: streamlab_celery
    command: celery -A streamlab worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://streamlab_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://streamlab_redis:6379/0
    networks:
      - appnet

  db:
    image: postgres:13
    container_name: streamlab_db
    environment:
      POSTGRES_DB: streamlab
      POSTGRES_USER: streamlab_user
      POSTGRES_PASSWORD: streamlab_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:6-alpine
    container_name: streamlab_redis
    # Removed sysctls because setting vm.overcommit_memory is not permitted in a separate container namespace.
    networks:
      appnet:
        aliases:
          - streamlab_redis

  srs:
    image: ossrs/srs:latest
    container_name: srs
    command: "./objs/srs -c conf/srs.conf"  # Adjust the path to your SRS configuration file as needed.
    ports:
      - "1935:1935"    # RTMP
      - "1985:1985"    # SRS REST API
      - "8080:8080"    # SRS HTTP (dashboard/web interface)
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
