# Generated by Django 5.1.2 on 2025-02-26 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "rtmp_url",
                    models.URLField(
                        help_text="RTMP endpoint provided by the streaming service"
                    ),
                ),
                (
                    "stream_key",
                    models.CharField(
                        help_text="Unique key for streaming", max_length=255
                    ),
                ),
                ("resolution", models.CharField(default="1080p", max_length=50)),
                ("bitrate", models.CharField(default="4500kbps", max_length=50)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this config is currently used for a live stream",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("error", "Error"),
                        ],
                        default="live",
                        max_length=50,
                    ),
                ),
                ("viewers_count", models.PositiveIntegerField(default=0)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="streaming.streamingconfiguration",
                    ),
                ),
            ],
        ),
    ]
