# Generated by Django 5.1.2 on 2025-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamingconfiguration",
            name="backup_rtmp_url",
            field=models.URLField(
                blank=True, help_text="Backup RTMP endpoint", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamingconfiguration",
            name="backup_stream_key",
            field=models.CharField(
                blank=True, help_text="Backup stream key", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="streamingconfiguration",
            name="embed_chat_url",
            field=models.URLField(
                blank=True, help_text="URL to embed multi-platform chat", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamingconfiguration",
            name="embed_player_url",
            field=models.URLField(
                blank=True, help_text="URL to embed the web player", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamingconfiguration",
            name="pull_links",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated or multi-line list of pull links",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Is this config currently active?"
            ),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="rtmp_url",
            field=models.URLField(help_text="RTMP endpoint (primary)"),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="stream_key",
            field=models.CharField(help_text="Unique stream key", max_length=255),
        ),
    ]
