# Generated by Django 5.1.2 on 2025-03-21 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_streamingconfiguration_backup_rtmp_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="streamingconfiguration",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("twitch", "Twitch"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("telegram", "Telegram"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for the streaming session",
                    ),
                ),
                ("text", models.TextField(help_text="The content of the chat message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the message was created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="scheduled_videos/"
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
