# Generated by Django 5.1.2 on 2025-03-21 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_streamingconfiguration_platform_chatmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="backup_rtmp_url",
            field=models.URLField(
                blank=True,
                help_text="Backup RTMP endpoint",
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "rtmp", "rtmps"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="embed_chat_url",
            field=models.URLField(
                blank=True,
                help_text="URL to embed multi-platform chat",
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "rtmp", "rtmps"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="embed_player_url",
            field=models.URLField(
                blank=True,
                help_text="URL to embed the web player",
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "rtmp", "rtmps"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="streamingconfiguration",
            name="rtmp_url",
            field=models.URLField(
                help_text="RTMP endpoint (primary)",
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "rtmp", "rtmps"]
                    )
                ],
            ),
        ),
    ]
