# Generated by Django 5.1.2 on 2025-04-02 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0004_streamingrelaystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamingplatformaccount",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Is this social account actively connected?"
            ),
        ),
        migrations.AlterField(
            model_name="streamingplatformaccount",
            name="account_username",
            field=models.CharField(
                blank=True,
                help_text="Username or channel name on the platform",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="streamingplatformaccount",
            name="rtmp_url",
            field=models.CharField(
                blank=True,
                help_text="RTMP URL for the account",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid URL. It should start with http, https, rtmp or rtmps.",
                        regex="^(https?|rtmps?|ftp)://.+$",
                    )
                ],
            ),
        ),
    ]
